server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///P:/Dev/Project/MSA
        git:
          uri: https://github.com/jaesin463/msa-study.git
          default-label: master
